/* tslint:disable */
/* eslint-disable */
/**
 * TilmanCloud Admin API
 * Cloud control plane API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Image {
    /**
     * AMI ID
     */
    'id': string;
    /**
     * AMI name
     */
    'name'?: string;
    /**
     * AMI state
     */
    'state': ImageStateEnum;
    /**
     * Content-based image identifier (from ImageID tag)
     */
    'imageId'?: string;
    /**
     * AMI creation date (ISO 8601)
     */
    'creationDate': string;
    /**
     * AMI description
     */
    'description'?: string;
    /**
     * Source snapshot ID (from SnapshotID tag)
     */
    'snapshotId'?: string;
    /**
     * Architecture type
     */
    'architecture': ImageArchitectureEnum;
    /**
     * Virtualization type
     */
    'virtualizationType': ImageVirtualizationTypeEnum;
}

export const ImageStateEnum = {
    Available: 'available',
    Pending: 'pending',
    Failed: 'failed',
    Deregistered: 'deregistered'
} as const;

export type ImageStateEnum = typeof ImageStateEnum[keyof typeof ImageStateEnum];
export const ImageArchitectureEnum = {
    Arm64: 'arm64',
    X8664: 'x86_64'
} as const;

export type ImageArchitectureEnum = typeof ImageArchitectureEnum[keyof typeof ImageArchitectureEnum];
export const ImageVirtualizationTypeEnum = {
    Hvm: 'hvm',
    Paravirtual: 'paravirtual'
} as const;

export type ImageVirtualizationTypeEnum = typeof ImageVirtualizationTypeEnum[keyof typeof ImageVirtualizationTypeEnum];


