/* tslint:disable */
/* eslint-disable */
/**
 * TilmanCloud Admin API
 * Cloud control plane API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Node {
    /**
     * Node name (EC2 instance ID)
     */
    'name': string;
    /**
     * Current node state
     */
    'state'?: NodeStateEnum;
    /**
     * EC2 instance type
     */
    'instanceType'?: string;
    /**
     * Public IP address
     */
    'publicIp'?: string | null;
    /**
     * Private IP address
     */
    'privateIp'?: string | null;
}

export const NodeStateEnum = {
    Pending: 'pending',
    Running: 'running',
    Stopping: 'stopping',
    Stopped: 'stopped',
    ShuttingDown: 'shutting-down',
    Terminated: 'terminated'
} as const;

export type NodeStateEnum = typeof NodeStateEnum[keyof typeof NodeStateEnum];


