apiVersion: v1
kind: Secret
metadata:
  name: clickhouse
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/instance: lab
    app.kubernetes.io/part-of: tilmancloud
    app.kubernetes.io/component: lab-only
stringData:
  password: clickhouse-lab
