apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouseservice
  namespace: tilmancloud-system
  labels:
    app.kubernetes.io/name: clickhouseservice
    app.kubernetes.io/part-of: tilmancloud
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clickhouseservice-manager
  labels:
    app.kubernetes.io/name: clickhouseservice
    app.kubernetes.io/part-of: tilmancloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clickhouseservice-manager
subjects:
  - kind: ServiceAccount
    name: clickhouseservice
    namespace: tilmancloud-system
